### PR TITLE
Copy to clipboard button

### PR DESCRIPTION
**Pull request by omichelsen**
Here's a quick and dirty "copy to clipboard" button implementation.

Does not seem to work for emojiis though :-/

### CODE REVIEW

**Comment by msiebuhr** [comment]
* I know you've taken the clipboard stuff from one of your own projects. Would you mind including a license/link to that?
* String.fromCharCode() doesn't handle surrogate pairs, so everything above 0xFFFF gets shafted, AFAIK. Probably why emojis doesn't work. From looking at MDN, we need [`fromCodePoint()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint), which probably needs polyfilling (it's missing in [IE + semi-old safaris](http://kangax.github.io/compat-table/es6/#String_static_methods_String.fromCodePoint)).

**Comment by omichelsen** [comment]
Yeah, this could be a polyfill solution: https://github.com/mathiasbynens/String.fromCodePoint

**Comment by msiebuhr** [comment]
Imported Mathias' polyfill + changed the code appropriately. Mind taking it for a spin?

**Comment by msiebuhr** [comment]
Finally, it seems to be missing some kind of feature-detection; the button is doing very little in Safari...

**Pull request merged**
